INSERT INTO TBDISCIPLINA (ID, CODIGO, NOME, EMENTA, CREDITOS, CARGAHORARIA, VERSION) VALUES (1, 'DCC010', 'Compiladores', null, 4, 60, 0)
INSERT INTO TBDISCIPLINA (ID, CODIGO, NOME, EMENTA, CREDITOS, CARGAHORARIA, VERSION) VALUES (2, 'DCC023', 'Rede de Computadores', null, 4, 60, 0)
INSERT INTO TBDISCIPLINA (ID, CODIGO, NOME, EMENTA, CREDITOS, CARGAHORARIA, VERSION) VALUES (3, 'MAT001', 'Cálculo Diferencial e Integral I', null, 6, 90, 0)
INSERT INTO TBDISCIPLINA (ID, CODIGO, NOME, EMENTA, CREDITOS, CARGAHORARIA, VERSION) VALUES (4, 'EST032', 'Probabilidade', null, 4, 60, 0)

